### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tuvqlu** [jasonwynn10/EasyCommandAutofill#11]
![image](https://user-images.githubusercontent.com/98550458/154758325-a92b4173-4180-4c0e-991c-2d9914593c10.jpeg)

**Comment by Tuvqlu** [comment]
Still crashes with newest plugin

**Comment by jasonw4331** [comment]
I can't read that. Link please

**Comment by jasonw4331** [comment]
Actually, the code in that screenshot doesn't even match the latest released version. Update your plugin.

**Comment by Tuvqlu** [comment]
Hello, i was using the most recent version and the same thing happens. However if I use 2.0.0 it does work

**Comment by jasonw4331** [comment]
"Most recent version" isn't a version number. Be specific please

**Comment by Tuvqlu** [comment]
Sorry, I was using 3.01
