### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by usser1976** [jasonwynn10/EasyCommandAutofill#3]
Is it possible to add permissions to players without op? For pay, msg and plot commands like addhelper and denyplayer it would be really handy for players.

**Comment by Wertzui123** [comment]
Why do you open an issue on EasyCommandAutofill if you're talking about adding permissions?

**Comment by usser1976** [comment]
Okay you're right, sorry.  I withdraw.

**Comment by usser1976** [comment]
unimportant, sorry.
