### ISSUE TITLE
All Commands Without Permission

### ISSUE THREAD

**Issue by suerion** [jasonwynn10/EasyCommandAutofill#5]
Hello Jason,

is it a bug, all my players could see the Commands, that they had no permissions? 

Its a little bit weired if it is normal.

**Comment by jasonw4331** [comment]
Please test the latest buid.

https://poggit.pmmp.io/r/90035/EasyCommandAutofill_dev-27.phar

**Comment by suerion** [comment]
Here the Permissions:
> permissions:
> - essentialstp.command.bedsethome
> - essentialstp.command.delhome
> - essentialstp.command.home
> - essentialstp.command.sethome
> - essentialstp.command.sign.spawn
> - essentialstp.command.sign.warp
> - essentialstp.command.spawn
> - essentialstp.command.tpa
> - essentialstp.command.tpaccept
> - essentialstp.command.tpahere
> - essentialstp.command.tpdeny
> - essentialstp.command.warp
> - myplot.claimplots.2
> - myplot.command.addhelper
> - myplot.command.auto
> - myplot.command.biome
> - myplot.command.biomes
> - myplot.command.claim
> - myplot.command.clear
> - myplot.command.denyplayer
> - myplot.command.dispose
> - myplot.command.done
> - myplot.command.generate
> - myplot.command.give
> - myplot.command.help
> - myplot.command.home
> - myplot.command.homes
> - myplot.command.info
> - myplot.command.list
> - myplot.command.middle
> - myplot.command.name
> - myplot.command.pvp
> - myplot.command.removehelper
> - myplot.command.undenyplayer
> - myplot.command.warp
> - pchat.coloredMessages
> - pocketmine.command.help
> - pocketmine.command.list
> - pocketmine.command.me
> - pocketmine.command.tell
> - pocketmine.command.transferserver
> - portalspe.portal.Minigames
> - skin.stealer
> - worldguard.enter.Plotwelt
> - worldguard.enter.global.Plotwelt
> - worldguard.leave.Plotwelt

https://gamerdvr.com/gamer/cronyu4/screenshot/16964870

do i need do hide the other commands? 
as shown on the screen:
skyblock
rg (worldguard)
mw (mw) 

the other commends are not shown as before
https://gamerdvr.com/gamer/cronyu4/screenshot/16963544

**Comment by efor89** [comment]
hi
I have the same problem I see as op but players without op see nothing. 
is there a permission I need to add?

**Comment by jasonw4331** [comment]
To see a command, players must be assigned the command's permission. Please check your permissions plugin to endure permissions are assigned properly.
